name: 01 - Building Blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: say hello
        run: echo "Hello, World!"
  echo-say-goodbye:
    runs-on: ubuntu-latest
    steps:
        - name: failed step
          run: | 
            exit 1
            echo "I will fail"
        - name: say goodbye
          run: echo "Goodbye, World!"


      




