name: 03 - Workflow Runners
on: push
jobs:
  ubuntu-job:
    name: ubuntu-echo
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "this step runs on Ubuntu-latest"
          echo "Runner: ${{ runner.os }}"
  windows-job:
    name: windows-echo
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "this step runs on Windows-latest
          echo "Runner: ${{ runner.os}}"
  macos-job:
    name: macos-echo
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "this step runs on MacOS-latest"
          echo "Runner: ${{ runner.os}}"
      


