name: 04 - Using Actions
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 04-using-action/react-app
        steps:
            - name: Checkout repository
              uses: Actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
               node-version: '20.x'
            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npm run test