name: 05 - 1 - filters - activity types
on: workflow_dispatch
   # pull_request:
       # types: [opened, synchronize]
     #   branches: 
       #     - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: message
              run: echo "Running whenever a PR is opened or updated on main branches"