name: 06 - Contexts

on:
    #push:
    workflow_dispatch:
        inputs:
          debug:
            description: "for debuging"
            type: boolean
            default: false

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        runs-on: ubuntu-latest
        steps:
            - name: echo-data
              run: |
               echo "Event name: ${{github.event_name}}"
               echo "Ref: ${{github.ref}}"
               echo "SHA: ${{github.sha}}"
               echo "Actor: ${{github.actor}}"
               echo "workflow: ${{github.workflow}}"
               echo "Run ID: ${{github.run_id}}"
               echo "Run nummber: ${{github.run_number}}"
            - name: retrieve Variable
              run: |
                echo "Variable value: ${{vars.MY_VAR}}"
            - name: Print Env variables
              env:
                MY_OVERWRITTEN_VAR: 'steps'
              run: |
               echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
               echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"
            - name: Print Env Variables
              run: |
               echo "workflow env: ${{env.MY_WORKFLOW_VAR}}"
               echo "workflow env: ${{env.MY_OVERWRITTEN_VAR}}"
