name: 08 - Using Variables

on: 
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: 'I am a workflow'
  OVERWRITTEN: 'I will be overwritten'

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
          JOB_VAR: 'I am a job env var'
          OVERWRITTEN: 'I have been overwritten at the job level'
        steps:
          - name: Print Env Variables
            env:
              STEP_VAR: 'I am a step env var'
              STEP_VAR2: 'I am another step var'
              OVERWRITTEN: 'I have been overwritten at the step level'
            run: |
              echo "Step env var: ${{env.STEP_VAR}}"
              echo "Step env var 2: $STEP_VAR2"
              echo "Job env var: $JOB_VAR"
              echo "Workflow env var: $WORKFLOW_VAR"
              echo "Overwritten: $OVERWRITTEN"
    
          - name: Overwrite_Job_Variable
            run: |
              echo "Step env var: $OVERWRITTEN"