name: 08 - veriables
on: 
  workflow_dispatch:
  push:
env:
  WORKFLOW_VAR: 'I am a workflow env'
  OVERWRITTEN_VAR: 'I will be overwritten'
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env'
      OVERWRITTEN_VAR: 'I have been overwritten at the job level'
    steps:
      - name: Print env variables
        env:
          step_var: 'I am a step env'
          step_var_2: 'I am another step env'
        run: |
          echo "step env var: $step_var"
          echo "steo env var 2: $step_var_2"
          echo "job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten var: $OVERWRITTEN_VAR"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN_VAR: 'I have been overwritten at the step level'
        run: |
          echo "step env var: $OVERWRITTEN_VAR"  