name: 09 - functions
on:
  workflow_dispatch:
  pull_request:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:

      - name: Print PR Title
        run: echo "Print PR title ${{ github.event.pull_request.title }}"
      - name: Print PR label
        run: |
          echo "Print PR labels cat 
          << EOF
            ${{ toJSON(github.event.pull_request.labels) }}
            EOF
      - name: Bug Step
        if: ${{ failure() && cancelled() == false && contains(github.event.pull_request.title || '', 'fix') }}
        run: echo "I am a bug fix"
      - name: sleep for 20 seconds
        run: sleep 20
      - name: failing step
        run: exit 1
      - name: will be skipped
        if: success()
        run: echo "I will print if any previous step success."
      - name: I will execute
        if: failure()
        run: echo "I will print if any previous step failure."
      - name: I will execute
        if: cancelled() == false
        run: echo ""I will always print, except when the workflow is cancelled"
      - name: I will execute when cancelled
        if: cancelled() == true
        run: echo "I will print if the workflow is cancelled."
      

             