name: 11 - working with Inputs

on:
    workflow_call:
    workflow_dispatch:
     inputs:
        dry-run:
          description: dry-run script
          type: boolean
          default: false
        target:
          description: "with environment workflow will target"
          type: environment
          required: true
        tag:
          type: choice
          options: [v1, v2, v3]
          default: v3
          description: 'Release from which to build and depoly'

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
        - name: build
          run: |
           echo "Building from tag ${{inputs.tag}}" 
    deploy:
      needs: build
      if: ${{ !inputs.dry-run}}
      runs-on: ubuntu-latest
      environment: ${{inputs.target}}
      steps:
        - name: Deploy
          run: |
           echo "Deploying to ${{inputs.target}}"

    
    