name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Set to true to do a dry run'
        type: boolean
        default: true
      target:
        description: 'Deployment target environment'
        type: environment
      tag:
        description: 'Tag to deploy'
        type: choice
        options:
          - v1.0
          - v1.1
          - v2.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Building from tag ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.dry-run == false }}
    environment: ${{inputs.target}}
    steps:
      - name: Deploy
        run: |
          echo "Deploying to environment ${{ inputs.target }}"


