name: 12 working with outputs
on: 
  workflow_dispatch:
    inputs:
      build-status:
        description: What is the status?
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
  build: 
   runs-on: ubuntu-latest
   outputs:
    build-status: ${{steps.build.output.status}}
   steps:
      - name: Print GITHUB_OUTPUT path
        run: "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: echo"status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: deploy
        run: echo "deploying..."


