name: 16 - Working with Environments
run-name: 16 - Working with environments | ${{inputs.target-env}}
on: 
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
                description: enviornment to deploy

jobs: 
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
             my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}

        steps:
            - name: Echo var
              run: |
                echo "Env variable: ${{env.my-env-value}}"
